import { Text, StyleSheet, TextInput, View, TouchableOpacity, ScrollView, ImageBackground, SafeAreaView, KeyboardAvoidingView, Platform, Modal, Image, Alert } from 'react-native';
export const styles = StyleSheet.create({
  background: { flex: 1 },
  container: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
    paddingBottom: 600,
  },
    introText: {
    fontSize: 20,
    color: "#2c3e50",
    marginBottom: 12,
    fontWeight: "600",
  },
  header1: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#fff",
  },
  logoLeft: {
    width: 80,
    height: 50,
  },
  logoRight: {
    width: 80,
    height: 50,
  },
  containerInner: {
    width: "100%",
    maxWidth: 960,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 12,
  },
  accordionBox: {
    flex: 1,
    marginHorizontal: 6,
  },
  fullWidthAccordion: {
    width: "100%",
    marginVertical: 8,
    paddingHorizontal: 6,
  },
  header: {
    backgroundColor: "#81cbfcff",
    padding: 12,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  content: {
    padding: 12,
    backgroundColor: "#fff",
    borderRadius: 8,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#ecf0f1",
  },
  subRow: {
    flex:1,
    flexDirection: "row",
    padding:2,
    justifyContent: "space-between",
    width: "100%",
  
    marginHorizontal: 6,
  },
  subAccordionBox: {
    flex: 1,
    marginHorizontal: 6,
  },
    subAccordionBoxx: {
    flex: 1,
    marginHorizontal: 6,
  },
  subHeader: {
    backgroundColor: "#16a085",
    padding: 10,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subHeaderText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 6,
    color: "#2c3e50",
  },
  labelSmall: {
    fontSize: 13,
    fontWeight: "500",
    marginBottom: 4,
    color: "#34495e",
  },
  input: {
    borderWidth: 1,
    borderColor: "#dfe6e9",
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    backgroundColor: "#fff",
  },
  textarea: {
    borderWidth: 1,
    borderColor: "#dfe6e9",
    borderRadius: 8,
    padding: 10,
    minHeight: 80,
    textAlignVertical: "top",
    backgroundColor: "#fff",
    marginBottom: 12,
  },
  pickerBox: {
    borderWidth: 1,
    borderColor: "#dfe6e9",
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 12,
    backgroundColor: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  personalInfoModal: {
    width: "100%",
    maxWidth: 760,
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    overflow: "hidden",
  },
  modalHeader: {
    backgroundColor: "#2c3e50",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  modalContent: {
    padding: 12,
    maxHeight: "75%",
  },
  modalFooter: {
    padding: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
    backgroundColor: "#fff",
  },
  modalButton: {
    backgroundColor: "#5ebfffff",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
  },
  modalButtonText: {
    color: "#862121ff",
    fontWeight: "600",
  },
  modalOption: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ecf0f1",
  },
  modalOptionText: {
    fontWeight: "600",
    fontSize: 14,
  },
  modalCancel: {
    marginTop: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  modalCancelText: {
    color: "#e74c3c",
    fontWeight: "700",
  },
  radioRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  radioContainer: {
    width: 36,
    justifyContent: "center",
    alignItems: "center",
  },
  radio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: "#7f8c8d",
    justifyContent: "center",
    alignItems: "center",
  },
  radioSelected: {
    borderColor: "#2980b9",
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#2980b9",
  },
  radioLabel: {
    marginLeft: 8,
    fontSize: 14,
    color: "#2c3e50",
  },
  buttonContainer: {
    width: "100%",
    paddingHorizontal: 6,
    marginTop: 12,
    marginBottom: 40,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  button: {
    flex: 1,
    backgroundColor: "#27ae60",
    paddingVertical: 12,
    borderRadius: 8,
    marginRight: 8,
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: "#ecf0f1",
    paddingVertical: 12,
    borderRadius: 8,
    marginLeft: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#bdc3c7",
  },
  secondaryButtonText: {
    color: "#2c3e50",
    fontWeight: "700",
    fontSize: 14,
  },
  expandableHeader: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e0e6ea",
    marginBottom: 8,
    backgroundColor: "#fff",
  },
  internalScroll: {
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  
});
export default styles;